name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Verify code quality
        run: uv run ruff check
      - name: Verify code style
        run: uv run ruff format --check
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - uses: astral-sh/setup-uv@v1
        with:
          version: latest
      - name: Install dependencies
        run: uv sync
      - name: Verify type hints
        run: uv run mypy
      - name: Run unit tests
        run: uv run python -m unittest
